(function () {
  "use strict";

  const ComicizeCalibration=Object.freeze({
    tilesAlongLongSide:64,
    density:Object.freeze({amplitude:.574,decay:38.25}),
    vignette:Object.freeze({p:2.79,c:.97286065,m:4.76388558}),
    luminanceTable:Object.freeze([[16,1.730],[32,1.410],[64,.667],[96,.253],[128,0],[160,-.247],[192,-.520],[224,-.760],[240,-.873]]),
    radius:Object.freeze({scale:.25,exponent:1.175}),
    baseOpacity:.5,
  });
  const COMICIZE_DEFAULTS=Object.freeze({enabled:true,colorBrush:0,dotDensity:50,dotFade:0,debugMode:"none",quantizeSmallRadii:false});
  const clamp=(value,low,high)=>Math.max(low,Math.min(high,value));
  function normalizeComicizeParams(params={}){const number=(value,fallback)=>Number.isFinite(Number(value))?Number(value):fallback;const allowed=new Set(["none","grid","luminance","luminanceTerm","densityTerm","radius","vignetteRadius","vignetteTerm","score","strength","alpha"]);const debugMode=allowed.has(params.debugMode)?params.debugMode:"none";return {enabled:params.enabled===undefined?true:!!params.enabled,colorBrush:clamp(number(params.colorBrush,0),0,100),dotDensity:clamp(number(params.dotDensity,50),0,100),dotFade:clamp(number(params.dotFade,0),0,100),debugMode,quantizeSmallRadii:!!params.quantizeSmallRadii};}
  function comicizeLuminance(r,g,b){return .299*r+.587*g+.114*b;}
  function getComicizeGridPhase(width,height,tileSize){const columns=Math.max(1,Math.ceil(width/tileSize)),rows=Math.max(1,Math.ceil(height/tileSize));return {originX:(width-columns*tileSize)/2,originY:(height-rows*tileSize)/2,columns,rows};}
  function getComicizeGrid(width,height){width=Math.max(1,Math.floor(Number(width)||1));height=Math.max(1,Math.floor(Number(height)||1));const tileSize=Math.max(1,Math.max(width,height)/ComicizeCalibration.tilesAlongLongSide),phase=getComicizeGridPhase(width,height,tileSize),tiles=[];for(let row=0;row<phase.rows;row++)for(let column=0;column<phase.columns;column++){const left=phase.originX+column*tileSize,top=phase.originY+row*tileSize,right=left+tileSize,bottom=top+tileSize;tiles.push({row,column,left,top,right,bottom,x0:clamp(Math.floor(left),0,width),y0:clamp(Math.floor(top),0,height),x1:clamp(Math.ceil(right),0,width),y1:clamp(Math.ceil(bottom),0,height),centerX:(left+right)/2,centerY:(top+bottom)/2});}return {width,height,tileSize,...phase,tiles};}
  function densityTerm(density){const c=ComicizeCalibration.density;return c.amplitude*(1-Math.exp(-clamp(Number(density)||0,0,100)/c.decay));}
  // TEMPORARY empirical calibration.
  // Replace after exact-RGB luminance calibration.
  function luminanceTerm(luminance){const table=ComicizeCalibration.luminanceTable,value=clamp(Number(luminance)||0,table[0][0],table[table.length-1][0]);for(let i=1;i<table.length;i++)if(value<=table[i][0]){const [x0,y0]=table[i-1],[x1,y1]=table[i],t=(value-x0)/(x1-x0);return y0+(y1-y0)*t;}return table[table.length-1][1];}
  function getComicizeVignette(x,y,width,height){const c=ComicizeCalibration.vignette,xn=(x-width/2)/(width/2),yn=(y-height/2)/(height/2),radius=Math.pow((Math.pow(Math.abs(xn),c.p)+Math.pow(Math.abs(yn),c.p))/2,1/c.p);return {radius,term:c.c*Math.pow(radius,c.m)};}
  function scoreToDotStrength(score){return clamp(score,0,1);}
  function dotStrengthToRadius(strength,tileSize,quantize=false){const c=ComicizeCalibration.radius;let radius=tileSize*c.scale*Math.pow(clamp(strength,0,1),c.exponent);if(quantize&&tileSize>0)radius=Math.round(radius/tileSize*64)/64*tileSize;return radius;}
  function buildLuminanceIntegral(source,width,height){const stride=width+1,integral=new Float64Array((width+1)*(height+1));for(let y=0;y<height;y++){let row=0;for(let x=0;x<width;x++){const i=(y*width+x)*4;row+=comicizeLuminance(source[i],source[i+1],source[i+2]);integral[(y+1)*stride+x+1]=integral[y*stride+x+1]+row;}}return {integral,stride};}
  function tileAverage(integral,stride,tile){const {x0,y0,x1,y1}=tile,count=Math.max(1,(x1-x0)*(y1-y0)),sum=integral[y1*stride+x1]-integral[y0*stride+x1]-integral[y1*stride+x0]+integral[y0*stride+x0];return sum/count;}
  function analyzeComicizeTiles(source,width,height,params={}){const p=normalizeComicizeParams(params),grid=getComicizeGrid(width,height),{integral,stride}=buildLuminanceIntegral(source,width,height),density=densityTerm(p.dotDensity),tiles=grid.tiles.filter(tile=>tile.x1>tile.x0&&tile.y1>tile.y0).map(tile=>{const luminance=tileAverage(integral,stride,tile),lumTerm=luminanceTerm(luminance),vignette=getComicizeVignette(tile.centerX,tile.centerY,width,height),score=lumTerm+density+vignette.term,strength=scoreToDotStrength(score),radius=dotStrengthToRadius(strength,grid.tileSize,p.quantizeSmallRadii),alpha=ComicizeCalibration.baseOpacity*strength*(1-p.dotFade/100);return {...tile,luminance,luminanceTerm:lumTerm,densityTerm:density,vignetteRadius:vignette.radius,vignetteTerm:vignette.term,score,strength,radius,alpha,pieceRadii:Object.freeze([radius,radius,radius,radius,radius])};});return {...grid,tiles,params:p};}
  function discCoverage(x,y,cx,cy,radius){if(radius<=0)return 0;return clamp(radius+.5-Math.hypot(x+.5-cx,y+.5-cy),0,1);}
  function debugValue(tile,mode){switch(mode){case"luminance":return tile.luminance/255;case"luminanceTerm":return clamp((tile.luminanceTerm+1)/2,0,1);case"densityTerm":return tile.densityTerm;case"radius":return tile.radius/Math.max(1,tile.right-tile.left)*4;case"vignetteRadius":return tile.vignetteRadius;case"vignetteTerm":return tile.vignetteTerm;case"score":return clamp((tile.score+1)/2,0,1);case"strength":return tile.strength;case"alpha":return tile.alpha;default:return 0;}}
  function applyComicizeToBuffer(source,width,height,params={}){if(!(source instanceof Uint8ClampedArray))throw new TypeError("source must be Uint8ClampedArray");width=Math.max(1,Math.floor(width));height=Math.max(1,Math.floor(height));const p=normalizeComicizeParams(params),output=source.slice(0,width*height*4);if(!p.enabled||p.dotFade>=100)return output;const analysis=analyzeComicizeTiles(source,width,height,p);for(const tile of analysis.tiles){if(p.debugMode!=="none"&&p.debugMode!=="grid"){const value=Math.round(clamp(debugValue(tile,p.debugMode),0,1)*255);for(let y=tile.y0;y<tile.y1;y++)for(let x=tile.x0;x<tile.x1;x++){const i=(y*width+x)*4;output[i]=output[i+1]=output[i+2]=value;}continue;}const points=[[tile.centerX,tile.centerY],[tile.left,tile.top],[tile.right,tile.top],[tile.left,tile.bottom],[tile.right,tile.bottom]];for(let y=tile.y0;y<tile.y1;y++)for(let x=tile.x0;x<tile.x1;x++){let coverage=0;for(const point of points)coverage=Math.max(coverage,discCoverage(x,y,point[0],point[1],tile.radius));const alpha=tile.alpha*coverage;if(alpha<=0)continue;const i=(y*width+x)*4;output[i]=Math.round(source[i]*(1-alpha));output[i+1]=Math.round(source[i+1]*(1-alpha));output[i+2]=Math.round(source[i+2]*(1-alpha));}if(p.debugMode==="grid"){for(let y=tile.y0;y<tile.y1;y++)for(let x=tile.x0;x<tile.x1;x++){const center=Math.hypot(x+.5-tile.centerX,y+.5-tile.centerY)<=1.25,corner=points.slice(1).some(point=>Math.hypot(x+.5-point[0],y+.5-point[1])<=1.25),boundary=x===tile.x0||y===tile.y0||x===tile.x1-1||y===tile.y1-1;if(center||corner||boundary){const i=(y*width+x)*4;output[i]=center?255:0;output[i+1]=boundary?255:0;output[i+2]=corner?255:0;}}}}return output;}
  function applyComicizeToCanvas(sourceCanvas,destinationCanvas,params={}){const context=sourceCanvas.getContext("2d",{willReadFrequently:true}),image=context.getImageData(0,0,sourceCanvas.width,sourceCanvas.height),data=applyComicizeToBuffer(image.data,image.width,image.height,params),output=destinationCanvas||document.createElement("canvas");output.width=image.width;output.height=image.height;output.getContext("2d").putImageData(new ImageData(data,image.width,image.height),0,0);return output;}
  window.ComicizeFilter={ComicizeCalibration,COMICIZE_DEFAULTS,normalizeComicizeParams,comicizeLuminance,getComicizeGridPhase,getComicizeGrid,densityTerm,luminanceTerm,getComicizeVignette,scoreToDotStrength,dotStrengthToRadius,analyzeComicizeTiles,applyComicizeToBuffer,applyComicizeToCanvas};
})();
