(function(){
  const HOLGA_SETTINGS=Object.freeze({monoAmount:1,redWeight:0.5234408203379078,greenWeight:0.4175670023063943,blueWeight:0.05899217735569784,exposure:0.017726232411417613,contrast:0.44227840375552,pivot:0.4564050987667964,gamma:0.9676626397690871,blackPoint:0.28073020918248964,whitePoint:0.35,sCurve:0.04155076135180802,vignetteStops:3.706613930390401,vignetteRadius:0.7987570669915517,vignetteSoftness:1.2250668844346377,roundness:1.3379912348822527,shape:5.155374457437444,centerX:0,centerY:0,cornerBurnStops:3.566199360306241,cornerPower:7.758670386731519});
  const HOLGA_IDENTITY=Object.freeze({monoAmount:0,redWeight:0.299,greenWeight:0.587,blueWeight:0.114,exposure:0,contrast:1,pivot:0.5,gamma:1,blackPoint:0,whitePoint:0,sCurve:0,vignetteStops:0,vignetteRadius:0.3,vignetteSoftness:1.1,roundness:1.04,shape:2.55,centerX:0,centerY:0,cornerBurnStops:0,cornerPower:3.2});
  const GEOMETRY_KEYS=new Set(['vignetteRadius','vignetteSoftness','roundness','shape','centerX','centerY','cornerBurnStops','cornerPower']);
  const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v));
  const smoothstep=(a,b,x)=>{const t=clamp((x-a)/Math.max(1e-6,b-a));return t*t*(3-2*t)};
  function sanitize(p){const o={...p},s=Math.max(1e-6,o.redWeight+o.greenWeight+o.blueWeight);o.redWeight/=s;o.greenWeight/=s;o.blueWeight/=s;return o}
  function profileAt(amount,settings=HOLGA_SETTINGS){const t=clamp(amount),o={};for(const k in settings)o[k]=GEOMETRY_KEYS.has(k)?settings[k]:HOLGA_IDENTITY[k]+(settings[k]-HOLGA_IDENTITY[k])*t;return sanitize(o)}
  function cornerMaskBase(x,y,w,h){const nx=(x-(w-1)/2)/Math.max(1e-6,(w-1)/2),ny=(y-(h-1)/2)/Math.max(1e-6,(h-1)/2);return Math.abs(nx*ny)}
  function opticalDistance(x,y,w,h,p){const cx=(.5+p.centerX)*(w-1),cy=(.5+p.centerY)*(h-1),scale=Math.max(1e-6,Math.min(w-1,h-1)/2),dx=(x-cx)/scale,dy=((y-cy)/scale)*p.roundness,shape=Math.max(1.0001,p.shape);return Math.pow(Math.pow(Math.abs(dx),shape)+Math.pow(Math.abs(dy),shape),1/shape)}
  function normalizeHolgaParams(params={}){return{fade:Math.max(0,Math.min(100,Number(params.fade ?? 0)||0))}}
  function applyHolgaRGBA(data,width,height,amount=1,settings=HOLGA_SETTINGS){const p=profileAt(amount,settings),out=new Uint8ClampedArray(data.length),ev=Math.pow(2,p.exposure),range=Math.max(1e-5,1-p.blackPoint-p.whitePoint);for(let y=0;y<height;y++){for(let x=0;x<width;x++){const i=(y*width+x)*4;let r=data[i]/255,g=data[i+1]/255,b=data[i+2]/255;const m=r*p.redWeight+g*p.greenWeight+b*p.blueWeight;r=r+(m-r)*p.monoAmount;g=g+(m-g)*p.monoAmount;b=b+(m-b)*p.monoAmount;r*=ev;g*=ev;b*=ev;const base=smoothstep(p.vignetteRadius,p.vignetteRadius+p.vignetteSoftness,opticalDistance(x,y,width,height,p)),corner=Math.pow(clamp(cornerMaskBase(x,y,width,height)),p.cornerPower),vf=Math.pow(2,-(p.vignetteStops*base+p.cornerBurnStops*corner));r*=vf;g*=vf;b*=vf;r=(r-p.pivot)*p.contrast+p.pivot;g=(g-p.pivot)*p.contrast+p.pivot;b=(b-p.pivot)*p.contrast+p.pivot;r=clamp(r);g=clamp(g);b=clamp(b);let z=r-.5;r+=p.sCurve*z*(1-4*z*z);z=g-.5;g+=p.sCurve*z*(1-4*z*z);z=b-.5;b+=p.sCurve*z*(1-4*z*z);r=clamp((r-p.blackPoint)/range);g=clamp((g-p.blackPoint)/range);b=clamp((b-p.blackPoint)/range);const gg=p.gamma;out[i]=Math.round(Math.pow(r,gg)*255);out[i+1]=Math.round(Math.pow(g,gg)*255);out[i+2]=Math.round(Math.pow(b,gg)*255);out[i+3]=data[i+3]}}return out}
  function applyHolgaIshToBuffer(source,width,height,params={}){const normalized=normalizeHolgaParams(params),original=new Uint8ClampedArray(source),filtered=applyHolgaRGBA(original,width,height,1,HOLGA_SETTINGS),fadeT=clamp(normalized.fade/100);if(fadeT<=0)return filtered;const out=new Uint8ClampedArray(filtered.length);for(let i=0;i<out.length;i+=4){out[i]=Math.round(filtered[i]+(original[i]-filtered[i])*fadeT);out[i+1]=Math.round(filtered[i+1]+(original[i+1]-filtered[i+1])*fadeT);out[i+2]=Math.round(filtered[i+2]+(original[i+2]-filtered[i+2])*fadeT);out[i+3]=original[i+3]}return out}
  function applyHolgaIshToImageData(imageData,params={}){return new ImageData(applyHolgaIshToBuffer(imageData.data,imageData.width,imageData.height,params),imageData.width,imageData.height)}
  function applyHolgaIshToCanvas(sourceCanvas,destinationCanvas=sourceCanvas,params={}){const ctx=sourceCanvas.getContext('2d',{willReadFrequently:true}),input=ctx.getImageData(0,0,sourceCanvas.width,sourceCanvas.height),output=applyHolgaIshToImageData(input,params);destinationCanvas.width=sourceCanvas.width;destinationCanvas.height=sourceCanvas.height;destinationCanvas.getContext('2d').putImageData(output,0,0);return destinationCanvas}
  window.HolgaFilter={HOLGA_SETTINGS,normalizeHolgaParams,applyHolgaRGBA,applyHolgaIshToBuffer,applyHolgaIshToImageData,applyHolgaIshToCanvas};
})();
