(function(){
  const ORTON_BLOOM_SETTINGS=Object.freeze({exposure:-0.396502,contrast:1,pivot:0.39477240320000007,blackPoint:0,whitePoint:0.19423087352319998,sCurve:0.6863051362227199,saturation:1.0294271705343998,temperature:0.00032115636735999785,tint:0.015654595279360042,gammaR:1.2645688775680002,gammaG:1.2301426218060798,gammaB:1.276943242432,blurRadius50:1.5,radiusCurve:0.743221,bloomBlend50:0.7175279376793596,blendCurve:0.06174912484351998,layerExposure:-0.11686621954047999,layerGamma:0.807490521088,postDarkening50:-0.099435803904,darkeningCurve:0.2867401117056});
  const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v));
  const mix=(a,b,t)=>a*(1-t)+b*t;
  const luma=(r,g,b)=>0.299*r+0.587*g+0.114*b;
  function clampPercent(value,fallback=0){const n=Number(value);return Math.max(0,Math.min(100,Number.isFinite(n)?n:fallback))}
  function normalizeOrtonParams(params={}){const p=params||{};return{bloom:clampPercent(p.bloom,25),fade:clampPercent(p.fade,0)}}
  function tonePassRGBA(data,p=ORTON_BLOOM_SETTINGS){const out=new Float32Array(data.length/4*3),gainR=Math.pow(2,p.temperature*.45+p.tint*.12),gainG=Math.pow(2,-p.tint*.24),gainB=Math.pow(2,-p.temperature*.45+p.tint*.12),ev=Math.pow(2,p.exposure),range=Math.max(1e-5,1-p.blackPoint-p.whitePoint);for(let i=0,j=0;i<data.length;i+=4,j+=3){let r=data[i]/255*gainR,g=data[i+1]/255*gainG,b=data[i+2]/255*gainB;const lum=luma(r,g,b);r=lum+p.saturation*(r-lum);g=lum+p.saturation*(g-lum);b=lum+p.saturation*(b-lum);r*=ev;g*=ev;b*=ev;r=(r-p.pivot)*p.contrast+p.pivot;g=(g-p.pivot)*p.contrast+p.pivot;b=(b-p.pivot)*p.contrast+p.pivot;r=clamp(r);g=clamp(g);b=clamp(b);let z=r-.5;r+=p.sCurve*z*(1-4*z*z);z=g-.5;g+=p.sCurve*z*(1-4*z*z);z=b-.5;b+=p.sCurve*z*(1-4*z*z);r=clamp((r-p.blackPoint)/range);g=clamp((g-p.blackPoint)/range);b=clamp((b-p.blackPoint)/range);out[j]=Math.pow(r,p.gammaR);out[j+1]=Math.pow(g,p.gammaG);out[j+2]=Math.pow(b,p.gammaB)}return out}
  function boxBlurRGB(src,w,h,radius){radius=Math.max(1,Math.round(radius));const tmp=new Float32Array(src.length),out=new Float32Array(src.length),div=radius*2+1;for(let y=0;y<h;y++){let rs=0,gs=0,bs=0;for(let k=-radius;k<=radius;k++){const x=Math.max(0,Math.min(w-1,k)),idx=(y*w+x)*3;rs+=src[idx];gs+=src[idx+1];bs+=src[idx+2]}for(let x=0;x<w;x++){const o=(y*w+x)*3;tmp[o]=rs/div;tmp[o+1]=gs/div;tmp[o+2]=bs/div;const xo=Math.max(0,x-radius),xi=Math.min(w-1,x+radius+1);let idx=(y*w+xo)*3;rs-=src[idx];gs-=src[idx+1];bs-=src[idx+2];idx=(y*w+xi)*3;rs+=src[idx];gs+=src[idx+1];bs+=src[idx+2]}}for(let x=0;x<w;x++){let rs=0,gs=0,bs=0;for(let k=-radius;k<=radius;k++){const y=Math.max(0,Math.min(h-1,k)),idx=(y*w+x)*3;rs+=tmp[idx];gs+=tmp[idx+1];bs+=tmp[idx+2]}for(let y=0;y<h;y++){const o=(y*w+x)*3;out[o]=rs/div;out[o+1]=gs/div;out[o+2]=bs/div;const yo=Math.max(0,y-radius),yi=Math.min(h-1,y+radius+1);let idx=(yo*w+x)*3;rs-=tmp[idx];gs-=tmp[idx+1];bs-=tmp[idx+2];idx=(yi*w+x)*3;rs+=tmp[idx];gs+=tmp[idx+1];bs+=tmp[idx+2]}}return out}
  function gaussianApprox(src,w,h,radius){if(radius<.55)return new Float32Array(src);const r=Math.max(1,Math.round(radius)),r1=Math.max(1,Math.round(r*.6));return boxBlurRGB(boxBlurRGB(src,w,h,r1),w,h,r1)}
  function applyOrtonBloomRGBA(data,width,height,bloom=25,p=ORTON_BLOOM_SETTINGS){const base=tonePassRGBA(data,p),n=clamp(bloom/50),out=new Uint8ClampedArray(data.length);if(n<=0||p.bloomBlend50<=0||p.blurRadius50<=0){for(let i=0,j=0;i<out.length;i+=4,j+=3){out[i]=Math.round(clamp(base[j])*255);out[i+1]=Math.round(clamp(base[j+1])*255);out[i+2]=Math.round(clamp(base[j+2])*255);out[i+3]=data[i+3]}return out}const radius=p.blurRadius50/100*Math.min(width,height)*Math.pow(n,p.radiusCurve),blur=gaussianApprox(base,width,height,radius),layerGain=Math.pow(2,p.layerExposure),blend=clamp(p.bloomBlend50*Math.pow(n,p.blendCurve)),postGain=Math.pow(2,p.postDarkening50*Math.pow(n,p.darkeningCurve));for(let i=0,j=0;i<out.length;i+=4,j+=3){const lr=Math.pow(clamp(blur[j]*layerGain),p.layerGamma),lg=Math.pow(clamp(blur[j+1]*layerGain),p.layerGamma),lb=Math.pow(clamp(blur[j+2]*layerGain),p.layerGamma),br=base[j],bg=base[j+1],bb=base[j+2],hr=lr<=.5?2*br*lr:1-2*(1-br)*(1-lr),hg=lg<=.5?2*bg*lg:1-2*(1-bg)*(1-lg),hb=lb<=.5?2*bb*lb:1-2*(1-bb)*(1-lb);out[i]=Math.round(clamp(mix(br,hr,blend)*postGain)*255);out[i+1]=Math.round(clamp(mix(bg,hg,blend)*postGain)*255);out[i+2]=Math.round(clamp(mix(bb,hb,blend)*postGain)*255);out[i+3]=data[i+3]}return out}
  function applyOrtonIshToBuffer(source,width,height,params={}){const normalized=normalizeOrtonParams(params),original=new Uint8ClampedArray(source),filtered=applyOrtonBloomRGBA(original,width,height,normalized.bloom,ORTON_BLOOM_SETTINGS),fadeT=clamp(normalized.fade/100);if(fadeT<=0)return filtered;const out=new Uint8ClampedArray(filtered.length);for(let i=0;i<out.length;i+=4){out[i]=Math.round(filtered[i]+(original[i]-filtered[i])*fadeT);out[i+1]=Math.round(filtered[i+1]+(original[i+1]-filtered[i+1])*fadeT);out[i+2]=Math.round(filtered[i+2]+(original[i+2]-filtered[i+2])*fadeT);out[i+3]=original[i+3]}return out}
  function applyOrtonIshToImageData(imageData,params={}){return new ImageData(applyOrtonIshToBuffer(imageData.data,imageData.width,imageData.height,params),imageData.width,imageData.height)}
  function applyOrtonIshToCanvas(sourceCanvas,destinationCanvas=sourceCanvas,params={}){const ctx=sourceCanvas.getContext('2d',{willReadFrequently:true}),input=ctx.getImageData(0,0,sourceCanvas.width,sourceCanvas.height),output=applyOrtonIshToImageData(input,params);destinationCanvas.width=sourceCanvas.width;destinationCanvas.height=sourceCanvas.height;destinationCanvas.getContext('2d').putImageData(output,0,0);return destinationCanvas}
  window.OrtonFilter={ORTON_BLOOM_SETTINGS,normalizeOrtonParams,tonePassRGBA,applyOrtonBloomRGBA,applyOrtonIshToBuffer,applyOrtonIshToImageData,applyOrtonIshToCanvas};
})();
