(function () {
  "use strict";

  const MODEL=window.PosterizeHierarchicalModel;
  const POSTERIZE_DEFAULTS=Object.freeze({colors:8,detail:100,modelVersion:MODEL?.version||"posterize-hierarchical-v12.1"});
  const clamp=(value,low,high)=>Math.max(low,Math.min(high,value));
  const preprocessingCache=new WeakMap(),statisticsCache=new WeakMap();
  function validatePosterizeModel(model){if(!model||model.version!=="posterize-hierarchical-v12.1")throw new Error("Unsupported Posterize calibration model");if(model.algorithm!=="classic-fixed-bit-rgb-octree"||!Array.isArray(model.detail?.anchors)||!model.octreeClassic||!model.transform)throw new Error("Invalid Posterize calibration model");return model;}
  validatePosterizeModel(MODEL);
  function normalizePosterizeParams(params={}){const colors=Number(params.colors),detail=Number(params.detail);return {colors:clamp(Math.round(Number.isFinite(colors)?colors:8),2,64),detail:clamp(Number.isFinite(detail)?detail:100,0,100),modelVersion:MODEL.version};}
  function interpolateDetail(detail,model=MODEL){const value=clamp(Number(detail)||0,0,100),anchors=model.detail.anchors;if(value<=anchors[0].detail)return {...anchors[0]};for(let i=1;i<anchors.length;i++)if(value<=anchors[i].detail){const a=anchors[i-1],b=anchors[i],t=(value-a.detail)/(b.detail-a.detail);return {detail:value,spatialSigma:a.spatialSigma+(b.spatialSigma-a.spatialSigma)*t,rangeSigma:a.rangeSigma+(b.rangeSigma-a.rangeSigma)*t};}return {...anchors[anchors.length-1]};}
  function classifyRoot(r,g,b){return `${r>=128?1:0}${g>=128?1:0}${b>=128?1:0}`;}
  function classifyTwoBitCell(r,g,b){return `${Math.min(3,r>>6)}${Math.min(3,g>>6)}${Math.min(3,b>>6)}`;}
  function getClassicExpansionPlan(colors,rootFractions={},model=MODEL){colors=clamp(Math.round(colors),2,64);const exposed=[];if(colors>=4)for(let parameter=4;parameter<=Math.min(colors,8);parameter++)for(const root of model.octreeClassic.rootExposureSteps[String(parameter)]||[])if((rootFractions[root]||0)>=model.octreeClassic.rootMinFraction)exposed.push(root);const refinements=[];for(let parameter=9;parameter<=Math.min(colors,13);parameter++){const refinement=model.octreeClassic.knownRefinements[String(parameter)];if(refinement)refinements.push({parameter,parent:refinement.parent,cells:refinement.cells.slice()});}if(colors>13)refinements.push(...getProvisionalFallbackRefinements(colors-13,model));return {colors,exposed,refinements};}
  // Provisional >13 behavior is deliberately isolated. The authoritative model
  // requests FIFO/first-appearance refinement; additional calibrated nodes can
  // replace this function without touching root semantics or pixel assignment.
  function getProvisionalFallbackRefinements(count,model=MODEL){const queue=["111","000",...model.octreeClassic.rootExposureOrder],result=[];for(let i=0;i<count;i++){const parent=queue[i%queue.length];result.push({parameter:14+i,parent,cells:[],fallback:true});}return result;}
  function classifyFixedBitCell(r,g,b,depth){const levels=1<<depth,shift=8-depth;return `${r>>shift},${g>>shift},${b>>shift}`;}
  function buildProvisionalFallbackRules(source,width,height,count,model=MODEL){const queue=["111","000",...model.octreeClassic.rootExposureOrder].map(root=>({depth:1,code:root.split("").join(",")})),rules=[];for(let step=0;step<count&&queue.length;step++){const parent=queue.shift(),depth=Math.min(model.octreeClassic.fallback.maxDepth,parent.depth+1),seen=new Set(),children=[];for(let p=0,i=0;p<width*height;p++,i+=4){if(source[i+3]===0)continue;const parentCode=classifyFixedBitCell(source[i],source[i+1],source[i+2],parent.depth);if(parentCode!==parent.code)continue;const code=classifyFixedBitCell(source[i],source[i+1],source[i+2],depth);if(!seen.has(code)){seen.add(code);children.push(code);}}if(children.length){rules.push({parameter:14+step,parent,depth,children});for(const code of children)queue.push({depth,code});}}return rules;}
  function gaussianWeights(sigma){const radius=Math.max(1,Math.ceil(sigma*3)),weights=new Float32Array(radius*2+1);for(let i=-radius;i<=radius;i++)weights[i+radius]=Math.exp(-(i*i)/(2*sigma*sigma));return {radius,weights};}
  function bilateralPass(source,width,height,sigmaSpatial,sigmaRange,horizontal){const output=new Uint8ClampedArray(source.length),{radius,weights}=gaussianWeights(sigmaSpatial),rangeDenominator=2*sigmaRange*sigmaRange;for(let y=0;y<height;y++)for(let x=0;x<width;x++){const index=(y*width+x)*4;let sums=[0,0,0],weightSum=0;for(let offset=-radius;offset<=radius;offset++){const sx=horizontal?clamp(x+offset,0,width-1):x,sy=horizontal?y:clamp(y+offset,0,height-1),sample=(sy*width+sx)*4,dr=source[sample]-source[index],dg=source[sample+1]-source[index+1],db=source[sample+2]-source[index+2],alphaWeight=source[sample+3]/255,weight=weights[offset+radius]*Math.exp(-(dr*dr+dg*dg+db*db)/rangeDenominator)*alphaWeight;sums[0]+=source[sample]*weight;sums[1]+=source[sample+1]*weight;sums[2]+=source[sample+2]*weight;weightSum+=weight;}if(weightSum>1e-12){output[index]=Math.round(sums[0]/weightSum);output[index+1]=Math.round(sums[1]/weightSum);output[index+2]=Math.round(sums[2]/weightSum);}else{output[index]=source[index];output[index+1]=source[index+1];output[index+2]=source[index+2];}output[index+3]=source[index+3];}return output;}
  function smoothPosterizeInput(source,width,height,detail,model=MODEL){const settings=interpolateDetail(detail,model);if(settings.spatialSigma<=1e-6||detail>=100)return source.slice();const scale=Math.max(width,height)/model.calibrationDim,sigma=Math.max(.05,settings.spatialSigma*scale),first=bilateralPass(source,width,height,sigma,settings.rangeSigma,true);return bilateralPass(first,width,height,sigma,settings.rangeSigma,false);}
  function getPreprocessed(source,width,height,detail){let entries=preprocessingCache.get(source);if(!entries){entries=new Map();preprocessingCache.set(source,entries);}const key=`${width}x${height}:${Number(detail).toFixed(4)}:${MODEL.version}`;if(!entries.has(key))entries.set(key,smoothPosterizeInput(source,width,height,detail));return entries.get(key);}
  function srgbToLinear(value){value/=255;return value<=.04045?value/12.92:Math.pow((value+.055)/1.055,2.4);}
  function linearToSrgb(value){value=clamp(value,0,1);return 255*(value<=.0031308?12.92*value:1.055*Math.pow(value,1/2.4)-.055);}
  function rgbToOklab(rgb){const r=srgbToLinear(rgb[0]),g=srgbToLinear(rgb[1]),b=srgbToLinear(rgb[2]),l=Math.cbrt(.4122214708*r+.5363325363*g+.0514459929*b),m=Math.cbrt(.2119034982*r+.6806995451*g+.1073969566*b),s=Math.cbrt(.0883024619*r+.2817188376*g+.6299787005*b);return [.2104542553*l+.793617785*m-.0040720468*s,1.9779984951*l-2.428592205*m+.4505937099*s,.0259040371*l+.7827717662*m-.808675766*s];}
  function oklabToRgb(lab){const l=Math.pow(lab[0]+.3963377774*lab[1]+.2158037573*lab[2],3),m=Math.pow(lab[0]-.1055613458*lab[1]-.0638541728*lab[2],3),s=Math.pow(lab[0]-.0894841775*lab[1]-1.291485548*lab[2],3);return [Math.round(linearToSrgb(4.0767416621*l-3.3077115913*m+.2309699292*s)),Math.round(linearToSrgb(-1.2684380046*l+2.6097574011*m-.3413193965*s)),Math.round(linearToSrgb(-.0041960863*l-.7034186147*m+1.707614701*s))];}
  function transformRepresentative(rgb,model=MODEL){const lab=rgbToOklab(rgb),matrix=model.transform.matrix,bias=model.transform.bias,transformed=matrix.map((row,i)=>row[0]*lab[0]+row[1]*lab[1]+row[2]*lab[2]+bias[i]);return oklabToRgb(transformed);}
  function collectStatistics(source,width,height){const roots=Object.fromEntries(["000","001","010","011","100","101","110","111"].map(key=>[key,{count:0,sum:[0,0,0]}])),cells={},total=width*height;let visible=0;for(let p=0,i=0;p<total;p++,i+=4){if(source[i+3]===0)continue;visible++;const rgb=[source[i],source[i+1],source[i+2]],root=classifyRoot(...rgb),cell=classifyTwoBitCell(...rgb);roots[root].count++;for(let c=0;c<3;c++)roots[root].sum[c]+=rgb[c];if(!cells[cell])cells[cell]={count:0,sum:[0,0,0],root};cells[cell].count++;for(let c=0;c<3;c++)cells[cell].sum[c]+=rgb[c];}const fractions={};for(const key in roots)fractions[key]=roots[key].count/Math.max(1,visible);return {roots,cells,fractions,visible};}
  function getCachedStatistics(source,width,height){const cached=statisticsCache.get(source);if(cached&&cached.width===width&&cached.height===height)return cached.statistics;const statistics=collectStatistics(source,width,height);statisticsCache.set(source,{width,height,statistics});return statistics;}
  const meanOf=stats=>stats&&stats.count?stats.sum.map(value=>value/stats.count):null;
  function combine(statsList){const aggregate={count:0,sum:[0,0,0]};for(const stats of statsList)if(stats){aggregate.count+=stats.count;for(let c=0;c<3;c++)aggregate.sum[c]+=stats.sum[c];}return aggregate;}
  function buildRegionAssignment(source,width,height,colors){const statistics=getCachedStatistics(source,width,height),plan=getClassicExpansionPlan(colors,statistics.fractions),fallbackRules=colors>13?buildProvisionalFallbackRules(source,width,height,colors-13):[],labels=new Array(width*height),regionStats={};for(let p=0,i=0;p<labels.length;p++,i+=4){const root=classifyRoot(source[i],source[i+1],source[i+2]),cell=classifyTwoBitCell(source[i],source[i+1],source[i+2]);let label;if(colors===2)label=(root==="110"||root==="111")?"light":"dark";else if(colors===3)label=root==="000"?"dark":root==="111"?"light":"middle";else label=root==="000"?"dark":root==="111"?"light":plan.exposed.includes(root)?`root:${root}`:"middle";for(const refinement of plan.refinements)if(!refinement.fallback&&root===refinement.parent&&refinement.cells.includes(cell))label=`cell:${cell}`;for(const rule of fallbackRules){const parentCode=classifyFixedBitCell(source[i],source[i+1],source[i+2],rule.parent.depth),childCode=classifyFixedBitCell(source[i],source[i+1],source[i+2],rule.depth);if(parentCode===rule.parent.code&&rule.children.includes(childCode))label=`d${rule.depth}:${childCode}`;}labels[p]=label;if(source[i+3]!==0){if(!regionStats[label])regionStats[label]={count:0,sum:[0,0,0]};regionStats[label].count++;regionStats[label].sum[0]+=source[i];regionStats[label].sum[1]+=source[i+1];regionStats[label].sum[2]+=source[i+2];}}return {labels,regionStats,statistics,plan,fallbackRules};}
  function specialRepresentative(label,assignment){const {statistics}=assignment;if(label==="dark")return meanOf(combine(MODEL.representatives.dark.cells.map(cell=>statistics.cells[cell])))||meanOf(statistics.roots["000"]);if(label==="light")return meanOf(combine(MODEL.representatives.light.roots.map(root=>statistics.roots[root])));if(label==="middle")return meanOf(combine(MODEL.representatives.middle.roots.map(root=>statistics.roots[root])));return null;}
  function renderClassicPosterize(source,width,height,params={}){const p=normalizePosterizeParams(params),smoothed=getPreprocessed(source,width,height,p.detail),assignment=buildRegionAssignment(smoothed,width,height,p.colors),global=meanOf(combine(Object.values(assignment.statistics.roots)))||[0,0,0],palette={};for(const label of new Set(assignment.labels)){const representative=specialRepresentative(label,assignment)||meanOf(assignment.regionStats[label])||global;palette[label]=transformRepresentative(representative);}const output=new Uint8ClampedArray(source.length);for(let pixel=0,index=0;pixel<assignment.labels.length;pixel++,index+=4){const color=palette[assignment.labels[pixel]];output[index]=color[0];output[index+1]=color[1];output[index+2]=color[2];output[index+3]=source[index+3];}return {data:output,palette,assignment,smoothed};}
  function applyPosterizeToBuffer(source,width,height,params={}){if(!(source instanceof Uint8ClampedArray))throw new TypeError("source must be Uint8ClampedArray");width=Math.max(1,Math.floor(width));height=Math.max(1,Math.floor(height));return renderClassicPosterize(source,width,height,params).data;}
  function applyPosterizeToCanvas(sourceCanvas,destinationCanvas,params={}){const context=sourceCanvas.getContext("2d",{willReadFrequently:true}),image=context.getImageData(0,0,sourceCanvas.width,sourceCanvas.height),data=applyPosterizeToBuffer(image.data,image.width,image.height,params),output=destinationCanvas||document.createElement("canvas");output.width=image.width;output.height=image.height;output.getContext("2d").putImageData(new ImageData(data,image.width,image.height),0,0);return output;}
  window.PosterizeFilter={MODEL,POSTERIZE_DEFAULTS,validatePosterizeModel,normalizePosterizeParams,interpolateDetail,classifyRoot,classifyTwoBitCell,getClassicExpansionPlan,getProvisionalFallbackRefinements,classifyFixedBitCell,buildProvisionalFallbackRules,smoothPosterizeInput,rgbToOklab,oklabToRgb,transformRepresentative,collectStatistics,buildRegionAssignment,renderClassicPosterize,applyPosterizeToBuffer,applyPosterizeToCanvas};
})();
