(function(){
  const SIXTIES_DEFAULTS = Object.freeze({exposure:0,contrast:-0.16,shadows:0,highlights:0,blackPoint:0.14,fade:0.17,printSoftness:0.16,saturation:1.15,vibrance:0,temperature:-0.61,tint:-0.42,redYellowBias:0.07,redHighlightLift:0,warmMidtoneLift:0,cyanShadowBias:0.01,gammaR:0.72,gammaG:0.89,gammaB:0.83,gainR:1.38,gainG:1.12,gainB:0.60,offsetR:0,offsetG:0,offsetB:0,vignette:0,glow:0.18,halation:0.14,grain:0});
  const clamp01=(v)=>Math.max(0,Math.min(1,v)); const lerp=(a,b,t)=>a+(b-a)*t;
  function rgbToHsl(r,g,b){const max=Math.max(r,g,b),min=Math.min(r,g,b),l=(max+min)/2;if(max===min)return[0,0,l];const d=max-min,s=l>0.5?d/(2-max-min):d/(max+min);let h;if(max===r)h=(g-b)/d+(g<b?6:0);else if(max===g)h=(b-r)/d+2;else h=(r-g)/d+4;return[h/6,s,l];}
  function hslToRgb(h,s,l){if(s===0)return[l,l,l];const q=l<0.5?l*(1+s):l+s-l*s,p=2*l-q;const hue=(t)=>{if(t<0)t+=1;if(t>1)t-=1;if(t<1/6)return p+(q-p)*6*t;if(t<1/2)return q;if(t<2/3)return p+(q-p)*(2/3-t)*6;return p;};return[hue(h+1/3),hue(h),hue(h-1/3)];}
  function toneCurve(v,softness){const t=clamp01(v),toe=t**(1+softness*.35),shoulder=1-(1-t)**(1-softness*.45);return lerp(toe,shoulder,.55)}
  function noise(x,y){const n=Math.sin(x*127.1+y*311.7)*43758.5453123;return n-Math.floor(n)}
  function applySixtiesFilter(imageData,overrides={}){const p={...SIXTIES_DEFAULTS,...overrides},{width,height,data:src}=imageData,out=new Uint8ClampedArray(src.length),cx=width/2,cy=height/2,maxDist=Math.hypot(cx,cy)||1,exposure=2**p.exposure;for(let y=0;y<height;y++){for(let x=0;x<width;x++){const i=(y*width+x)*4;let r=src[i]/255,g=src[i+1]/255,b=src[i+2]/255;r*=exposure;g*=exposure;b*=exposure;r=clamp01(r)**(1/p.gammaR)*p.gainR+p.offsetR/255;g=clamp01(g)**(1/p.gammaG)*p.gainG+p.offsetG/255;b=clamp01(b)**(1/p.gammaB)*p.gainB+p.offsetB/255;const luma=clamp01(.299*r+.587*g+.114*b),shadows=(1-luma)**1.5,highlights=luma**1.4,mids=Math.max(0,1-Math.abs(luma-.5)*2),common=p.shadows*shadows+p.highlights*highlights;r+=common;g+=common;b+=common;r+=p.redYellowBias*(.65*mids+.25*highlights);g+=p.redYellowBias*.25*mids;r+=p.redHighlightLift*(.2*mids+.8*highlights);g+=p.redHighlightLift*.08*highlights;r+=p.warmMidtoneLift*.75*mids;g+=p.warmMidtoneLift*.28*mids;b-=p.warmMidtoneLift*.18*mids;g+=p.cyanShadowBias*.2*shadows;b+=p.cyanShadowBias*.55*shadows;const avg=(r+g+b)/3,contrast=1+p.contrast;r=avg+(r-avg)*contrast;g=avg+(g-avg)*contrast;b=avg+(b-avg)*contrast;r+=p.temperature*.15-p.tint*.02;g+=p.tint*.06;b-=p.temperature*.14+p.tint*.04;let [h,s,l]=rgbToHsl(clamp01(r),clamp01(g),clamp01(b));s=clamp01(s*p.saturation+(1-s)*p.vibrance*.35);h=(h+p.glow*.01-p.cyanShadowBias*.005+1)%1;[r,g,b]=hslToRgb(h,s,l);r=toneCurve(r,p.printSoftness);g=toneCurve(g,p.printSoftness);b=toneCurve(b,p.printSoftness);const halo=p.halation*highlights**1.8;r+=halo*.9;g+=halo*.45;b+=halo*.15;const distance=Math.hypot(x-cx,y-cy)/maxDist,vignette=1-p.vignette*distance*distance;r=r*vignette+p.fade*.94;g=g*vignette+p.fade*.91;b=b*vignette+p.fade*.86;const blackScale=Math.max(.0001,1-p.blackPoint);r=(r-p.blackPoint)/blackScale;g=(g-p.blackPoint)/blackScale;b=(b-p.blackPoint)/blackScale;if(p.grain!==0){const grain=(noise(x,y)-.5)*p.grain;r+=grain;g+=grain*.9;b+=grain*.8}out[i]=Math.round(clamp01(r)*255);out[i+1]=Math.round(clamp01(g)*255);out[i+2]=Math.round(clamp01(b)*255);out[i+3]=src[i+3];}}return new ImageData(out,width,height)}
  function applySixtiesFilterToCanvas(sourceCanvas,destinationCanvas=sourceCanvas,overrides={}){const sourceContext=sourceCanvas.getContext('2d',{willReadFrequently:true}),width=sourceCanvas.width,height=sourceCanvas.height,input=sourceContext.getImageData(0,0,width,height),output=applySixtiesFilter(input,overrides);destinationCanvas.width=width;destinationCanvas.height=height;destinationCanvas.getContext('2d').putImageData(output,0,0);return destinationCanvas}
  window.SixtiesFilter={SIXTIES_DEFAULTS,applySixtiesFilter,applySixtiesFilterToCanvas};
})();
