const assert=require("assert"),fs=require("fs"),vm=require("vm");
const sandbox={window:{},Uint8ClampedArray,Math};vm.createContext(sandbox);vm.runInContext(fs.readFileSync("drop-shadow-filter.js","utf8"),sandbox);const D=sandbox.window.DropShadowFilter;
assert.deepStrictEqual(JSON.parse(JSON.stringify(D.getDropShadowOffset(30,0))),{dx:30,dy:0});
assert.deepStrictEqual(JSON.parse(JSON.stringify(D.getDropShadowOffset(30,180))),{dx:-30,dy:0});
assert.deepStrictEqual(JSON.parse(JSON.stringify(D.getDropShadowOffset(30,86.400009))),{dx:1,dy:29});
assert.deepStrictEqual(JSON.parse(JSON.stringify(D.getDropShadowOffset(30,42.105263))),{dx:22,dy:20});
assert.deepStrictEqual(JSON.parse(JSON.stringify(D.getDropShadowOffset(30,360))),{dx:30,dy:0});
assert.deepStrictEqual([D.getDropShadowSupportPadding(0),D.getDropShadowSupportPadding(10),D.getDropShadowSupportPadding(50.000011),D.getDropShadowSupportPadding(100)],[2,14,68,136]);
assert.strictEqual(D.getDropShadowSigma(10),3.5);assert.strictEqual(D.getDropShadowSigma(100),35);
const approx=(a,b,e=1e-6)=>assert.ok(Math.abs(a-b)<=e,`${a} != ${b}`);
approx(D.getDropShadowFadeFactor(0),1);approx(D.getDropShadowFadeFactor(30),.4522774425);approx(D.getDropShadowFadeFactor(50),.2928932188);approx(D.getDropShadowFadeFactor(100),0);
for(let f=0;f<100;f++)assert.ok(D.getDropShadowFadeFactor(f)>=D.getDropShadowFadeFactor(f+1));
assert.deepStrictEqual([D.normalizeDropShadowColor("00000000"),D.normalizeDropShadowColor("00ffffff"),D.normalizeDropShadowColor("ff79b3db"),D.normalizeDropShadowColor("fff3f8ff")],["#000000","#ffffff","#79b3db","#f3f8ff"]);
let g=D.getDropShadowGeometry(1076,980,{distance:30,angle:86.400009,size:0});assert.deepStrictEqual([g.dx,g.dy,g.supportPadding,g.outputWidth,g.outputHeight,g.imageX,g.imageY],[1,29,2,1080,1011,1,0]);
g=D.getDropShadowGeometry(1076,980,{distance:30,angle:0,size:10});assert.deepStrictEqual([g.supportPadding,g.outputWidth,g.outputHeight,g.imageX,g.imageY],[14,1120,1008,0,14]);
g=D.getDropShadowGeometry(411,1569,{distance:0,angle:0,size:100});assert.deepStrictEqual([g.outputWidth,g.outputHeight,g.imageX,g.imageY],[683,1841,136,136]);
g=D.getDropShadowGeometry(411,1569,{distance:0,angle:0,size:50.000011});assert.deepStrictEqual([g.outputWidth,g.outputHeight,g.imageX,g.imageY],[547,1705,68,68]);
const src=new Uint8ClampedArray([12,34,56,123,78,90,111,255]);let r=D.applyDropShadowToBuffer(src,2,1,{enabled:false});assert.deepStrictEqual([r.width,r.height],[2,1]);assert.deepStrictEqual(Array.from(r.data),Array.from(src));
const rasterParams={enabled:true,distance:3,angle:0,size:0,shadowColor:"00000000",backgroundColor:"00ffffff",fade:0};g=D.getDropShadowGeometry(2,1,rasterParams);r=D.applyDropShadowToBuffer(src,2,1,rasterParams);const first=(g.imageY*r.width+g.imageX)*4;assert.deepStrictEqual(Array.from(r.data.slice(first,first+8)),Array.from(src),"source bytes copied unchanged");for(let i=3;i<r.data.length;i+=4)if(i<first||i>=first+8)assert.strictEqual(r.data[i],255,"output background/shadow alpha stays opaque");
const html=fs.readFileSync("index.html","utf8");assert.match(html,/DropShadow=\$\{p\.enabled\?1:0\}/);assert.match(html,/applyDropShadowToCanvas/);assert.match(html,/<b>Effects &amp; Finishes<\/b>[\s\S]*btnDropShadowMode/);assert.match(html,/mapPointThroughFilterChain[\s\S]*parseDropShadowFilter/);
console.log("drop-shadow-filter tests passed");
