const assert=require("assert"),fs=require("fs"),vm=require("vm");
const sandbox={window:{},Uint8ClampedArray,Float32Array,Math};vm.createContext(sandbox);vm.runInContext(fs.readFileSync("pencil-sketch-filter.js","utf8"),sandbox);const P=sandbox.window.PencilSketchFilter,plain=x=>JSON.parse(JSON.stringify(x));
assert.deepStrictEqual(plain(P.normalizePencilSketchParams({radius:0,strength:-1,fade:200})),{enabled:true,radius:1.3,strength:0,fade:100});assert.deepStrictEqual(plain(P.normalizePencilSketchParams({radius:8,strength:250,fade:-2})),{enabled:true,radius:5,strength:200,fade:0});
assert.strictEqual(P.radiusToDiscreteKernel(2.855731),3);assert.strictEqual(P.radiusToDiscreteKernel(2.975170),3);assert.strictEqual(P.radiusToDiscreteKernel(3.242608),3);assert.ok(P.strengthToDetailGain(0)<P.strengthToDetailGain(100)&&P.strengthToDetailGain(100)<P.strengthToDetailGain(200));
const uniform=(value,alpha=123)=>{const data=new Uint8ClampedArray(9*7*4);for(let i=0;i<data.length;i+=4)data.set([value,value,value,alpha],i);return data;};for(const value of [0,255,127]){const source=uniform(value),output=P.applyPencilSketchToBuffer(source,9,7,{});for(let i=0;i<output.length;i+=4){assert.ok(output[i]>=254&&output[i+1]>=254&&output[i+2]>=254,"uniform field becomes white paper");assert.strictEqual(output[i+3],source[i+3]);}}
const width=17,height=13,source=new Uint8ClampedArray(width*height*4);for(let y=0;y<height;y++)for(let x=0;x<width;x++){const i=(y*width+x)*4,v=(x<8?25:220)+((x*17+y*29)%31);source.set([Math.min(255,v),Math.min(255,v/2+30),Math.min(255,255-v/3),80+(x+y)%170],i);}
for(const params of [{enabled:false},{fade:100}])assert.deepStrictEqual(Array.from(P.applyPencilSketchToBuffer(source,width,height,params)),Array.from(source));
const radiusLow=P.applyPencilSketchToBuffer(source,width,height,{radius:1.3,strength:100}),radiusHigh=P.applyPencilSketchToBuffer(source,width,height,{radius:5,strength:100});assert.notDeepStrictEqual(Array.from(radiusLow),Array.from(radiusHigh),"radius changes spatial scale");
const strength0=P.applyPencilSketchToBuffer(source,width,height,{radius:2,strength:0}),strength100=P.applyPencilSketchToBuffer(source,width,height,{radius:2,strength:100}),strength200=P.applyPencilSketchToBuffer(source,width,height,{radius:2,strength:200});assert.notDeepStrictEqual(Array.from(strength0),Array.from(strength100));assert.notDeepStrictEqual(Array.from(strength100),Array.from(strength200));
for(let i=0;i<strength100.length;i+=4){assert.strictEqual(strength100[i],strength100[i+1]);assert.strictEqual(strength100[i+1],strength100[i+2],"pure sketch is grayscale");assert.strictEqual(strength100[i+3],source[i+3],"alpha preserved");}
const half=P.applyPencilSketchToBuffer(source,width,height,{radius:2,strength:100,fade:50});for(let i=0;i<half.length;i+=4)for(let c=0;c<3;c++)assert.ok(Math.abs(half[i+c]-Math.round((strength100[i+c]+source[i+c])/2))<=1);assert.strictEqual(half.length,source.length);
const html=fs.readFileSync("index.html","utf8");assert.match(html,/PencilSketch=\$\{p\.enabled\?1:0\}/);assert.match(html,/applyPencilSketchToCanvas/);assert.match(html,/<b>Effects &amp; Finishes<\/b>[\s\S]*btnPencilSketchMode/);assert.match(html,/function parsePencilSketchFilter/);
console.log("pencil-sketch-filter tests passed");
