const assert=require("assert"),fs=require("fs"),vm=require("vm");
const sandbox={window:{},Uint8ClampedArray,Math};vm.createContext(sandbox);vm.runInContext(fs.readFileSync("polaroid-filter.js","utf8"),sandbox);const P=sandbox.window.PolaroidFilter,plain=value=>JSON.parse(JSON.stringify(value));
let g=P.getPolaroidGeometry(411,1569,0);assert.deepStrictEqual(plain(g.cropRect),{x:0,y:579,width:411,height:411});assert.deepStrictEqual([g.sideBorder,g.topBorder,g.bottomBorder],[27,40,106]);assert.deepStrictEqual(plain(g.paperRect),{x:11,y:8,width:465,height:557});assert.deepStrictEqual(plain(g.photoRect),{x:38,y:48,width:411,height:411});assert.deepStrictEqual([g.baseWidth,g.baseHeight,g.outputWidth,g.outputHeight],[487,579,487,579]);
g=P.getPolaroidGeometry(1626,700,0);assert.deepStrictEqual(plain(g.cropRect),{x:463,y:0,width:700,height:700});assert.deepStrictEqual([g.sideBorder,g.topBorder,g.bottomBorder],[45,68,181]);assert.deepStrictEqual(plain(g.paperRect),{x:11,y:8,width:790,height:949});assert.deepStrictEqual(plain(g.photoRect),{x:56,y:76,width:700,height:700});assert.deepStrictEqual([g.baseWidth,g.baseHeight,g.outputWidth,g.outputHeight],[812,971,812,971]);
assert.deepStrictEqual([P.getPolaroidGeometry(411,1569,-10).outputWidth,P.getPolaroidGeometry(411,1569,-10).outputHeight],[580,654]);assert.deepStrictEqual([P.getPolaroidGeometry(411,1569,5).outputWidth,P.getPolaroidGeometry(411,1569,5).outputHeight],[535,619]);assert.deepStrictEqual([P.getPolaroidGeometry(1626,700,10).outputWidth,P.getPolaroidGeometry(1626,700,10).outputHeight],[968,1097]);assert.deepStrictEqual([P.getPolaroidGeometry(411,1569,10).outputWidth,P.getPolaroidGeometry(411,1569,-10).outputWidth],[580,580]);
assert.deepStrictEqual([P.normalizePolaroidColor("00e2e2e2"),P.normalizePolaroidColor("ffffffff"),P.normalizePolaroidColor("ff000702")],["#e2e2e2","#ffffff","#000702"]);assert.deepStrictEqual(plain(P.normalizePolaroidParams({})),{enabled:true,rotate:5,backgroundColor:"#e2e2e2"});
const width=4,height=2,source=new Uint8ClampedArray(width*height*4);for(let y=0;y<height;y++)for(let x=0;x<width;x++){const i=(y*width+x)*4;source.set([x,y,10+x+y,100+x],i);}let result=P.applyPolaroidToBuffer(source,width,height,{enabled:false});assert.deepStrictEqual([result.width,result.height],[width,height]);assert.deepStrictEqual(Array.from(result.data),Array.from(source));
result=P.applyPolaroidToBuffer(source,width,height,{enabled:true,rotate:0,backgroundColor:"00e2e2e2"});g=P.getPolaroidGeometry(width,height,0);for(let y=0;y<g.squareSize;y++){const si=((g.cropRect.y+y)*width+g.cropRect.x)*4,di=((g.photoRect.y+y)*result.width+g.photoRect.x)*4;assert.deepStrictEqual(Array.from(result.data.slice(di,di+g.squareSize*4)),Array.from(source.slice(si,si+g.squareSize*4)),"native crop bytes are copied exactly");}
const html=fs.readFileSync("index.html","utf8");assert.match(html,/Polaroid=\$\{p\.enabled\?1:0\}/);assert.match(html,/applyPolaroidToCanvas/);assert.match(html,/<b>Effects &amp; Finishes<\/b>[\s\S]*btnPolaroidMode/);assert.match(html,/polaroidRotateInput[^>]*min="-10" max="10"[^>]*value="5"/);
console.log("polaroid-filter tests passed");
