const assert=require("assert"),fs=require("fs"),vm=require("vm");
const json=JSON.parse(fs.readFileSync("posterize-hierarchical-model.json","utf8")),sandbox={window:{},Uint8ClampedArray,Float32Array,Math,Map,WeakMap,Set,Object};vm.createContext(sandbox);vm.runInContext(fs.readFileSync("posterize-hierarchical-model.js","utf8"),sandbox);assert.deepStrictEqual(JSON.parse(JSON.stringify(sandbox.window.PosterizeHierarchicalModel)),json,"JS artifact mirrors authoritative JSON");vm.runInContext(fs.readFileSync("posterize-filter.js","utf8"),sandbox);const P=sandbox.window.PosterizeFilter,plain=x=>JSON.parse(JSON.stringify(x));
assert.strictEqual(P.MODEL.version,"posterize-hierarchical-v12.1");assert.strictEqual(P.classifyRoot(127,127,127),"000");assert.strictEqual(P.classifyRoot(128,128,128),"111");assert.strictEqual(P.classifyRoot(127,128,127),"010");
const octants=[[32,32,32],[32,32,224],[32,224,32],[32,224,224],[224,32,32],[224,32,224],[224,224,32],[224,224,224]],source=new Uint8ClampedArray(octants.length*4);octants.forEach((rgb,i)=>source.set([...rgb,40+i],i*4));
let assignment=P.buildRegionAssignment(source,8,1,2);assert.deepStrictEqual(plain(assignment.labels),["dark","dark","dark","dark","dark","dark","light","light"]);
assignment=P.buildRegionAssignment(source,8,1,3);assert.deepStrictEqual(plain(assignment.labels),["dark","middle","middle","middle","middle","middle","middle","light"]);
const fractions=Object.fromEntries(["000","001","010","011","100","101","110","111"].map(key=>[key,.125]));let plan=P.getClassicExpansionPlan(8,fractions);assert.deepStrictEqual(plain(plan.exposed),["110","100","101","010","001","011"]);
const expected={9:["111",["222","333"]],10:["000",["000","111"]],11:["110",["220","331"]],12:["100",["210","310"]],13:["010",["121"]]};for(let colors=9;colors<=13;colors++){plan=P.getClassicExpansionPlan(colors,fractions);const refinement=plan.refinements.find(item=>item.parameter===colors);assert.deepStrictEqual(plain([refinement.parent,refinement.cells]),expected[colors]);}
const width=16,height=8,image=new Uint8ClampedArray(width*height*4);for(let y=0;y<height;y++)for(let x=0;x<width;x++){const i=(y*width+x)*4;image.set([(x*37+y*13)%256,(x*11+y*41)%256,(x*23+y*7)%256,(x+y)%5?255:0],i);}
const render8=P.renderClassicPosterize(image,width,height,{colors:8,detail:100}),render9=P.renderClassicPosterize(image,width,height,{colors:9,detail:100});for(const label of Object.keys(render8.palette))if(render9.palette[label])assert.deepStrictEqual(render8.palette[label],render9.palette[label],`existing representative ${label} remains stable`);
assert.ok(Object.keys(render9.palette).length!==9,"Colors expansion index need not equal palette size");const paletteValues=new Set(Object.values(render9.palette).map(rgb=>rgb.join(",")));for(let i=0;i<render9.data.length;i+=4){assert.ok(paletteValues.has([render9.data[i],render9.data[i+1],render9.data[i+2]].join(",")),"output is an exact palette entry");assert.strictEqual(render9.data[i+3],image[i+3]);}
assert.deepStrictEqual(Array.from(P.applyPosterizeToBuffer(image,width,height,{colors:11,detail:42})),Array.from(P.applyPosterizeToBuffer(image,width,height,{colors:11,detail:42})),"repeat rendering deterministic");
const d0=P.smoothPosterizeInput(image,width,height,0),d50=P.smoothPosterizeInput(image,width,height,50),d100=P.smoothPosterizeInput(image,width,height,100),difference=data=>data.reduce((sum,value,index)=>index%4===3?sum:sum+Math.abs(value-image[index]),0);assert.ok(difference(d0)>=difference(d50),"increasing Detail reduces smoothing");assert.strictEqual(difference(d100),0,"Detail 100 has no smoothing");
assert.deepStrictEqual(plain(P.normalizePosterizeParams({colors:1,detail:200})),{colors:2,detail:100,modelVersion:"posterize-hierarchical-v12.1"});
const html=fs.readFileSync("index.html","utf8");assert.match(html,/Posterize=1,\$\{p\.colors\}/);assert.match(html,/applyPosterizeToCanvas/);assert.match(html,/<b>Looks &amp; Color Styles<\/b>[\s\S]*btnPosterizeMode/);assert.match(html,/posterizeColorsInput[^>]*min="2" max="64"/);
console.log("posterize-filter tests passed");
